POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 5
}

###
DELETE  http://localhost:3003/api/blogs/62e036c9a58f2fb25819acea

###
PUT http://localhost:3003/api/blogs/62e038ebac97cb402e33530d
Content-Type: application/json

{
    "likes": 10
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "ro",
    "name": "test",
    "passwordHash": "test"
}